[package]
name = "rhai-sci"
version = "0.1.5"
edition = "2021"
authors = ["Chris McComb <ccmcc2012@gmail.com>"]
description = "Scientific computing in the Rhai scripting language"
repository = "https://github.com/cmccomb/rhai-sci"
homepage = "https://github.com/cmccomb/rhai-sci"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["scripting", "rhai", "scientific", "scripting-language", "matlab"]
categories = ["algorithms", "science"]
documentation = "https://docs.rs/rhai-sci"
build = "build.rs"

[dependencies]
rhai = { version = "1.5", features = ["unchecked", "serde", "metadata"]}
rhai-rand = "0.1.3"


[build-dependencies]
rhai = { version = "1.5", features = ["unchecked", "serde", "metadata"]}
itertools = "0.10.3"
rhai-rand = "0.1.3"
