[package]
name = "rhai-sci"
version = "0.1.6"
edition = "2021"
authors = ["Chris McComb <ccmcc2012@gmail.com>"]
description = "Scientific computing in the Rhai scripting language"
repository = "https://github.com/rhaiscript/rhai-sci"
homepage = "https://github.com/rhaiscript/rhai-sci"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["scripting", "rhai", "scientific", "scripting-language", "matlab"]
categories = ["algorithms", "science"]
documentation = "https://docs.rs/rhai-sci"
build = "build.rs"

[features]
metadata = ["rhai/metadata"]

[dependencies]
rhai = "1.8"
rustyline = "10.0.0"
nalgebra = "0.30.1"
polars = "0.17.0"
url = "2.2.2"
temp-file = "0.1.6"
csv-sniffer = "0.1.1"
minreq = { version = "2.6.0", features = ["json-using-serde", "https"] }
rand = "0.8"
smartstring = "1.0.1"

[build-dependencies]
rhai = "1.8"
itertools = "0.10.3"
nalgebra = "0.30.1"
polars = "0.17.0"
url = "2.2.2"
temp-file = "0.1.6"
csv-sniffer = "0.1.1"
minreq = { version = "2.6.0", features = ["json-using-serde", "https"] }
rand = "0.8"
serde_json = "1.0.82"
serde = "1.0.140"
smartstring = "1.0.1"

[package.metadata.docs.rs]
features = ["metadata"]
